### PR TITLE
support type parameters

### PR DESCRIPTION
**Pull request by windrunner414**
#3

### CODE REVIEW

**Comment by numen31337** [comment]
@windrunner414 thank you for submitting this pull request. Unfortunately, this solution will not work with more complex cases than just having a `T` parameter of some basic type like `String`.
Think of something like this:
```dart
class SubClass<T, U extends String> extends BasicClass
    with TestMix
    implements AClass {
///...
}
```

**Comment by windrunner414** [comment]
@numen31337 you mean the 'U extends String'? I think we can ignore the extends because dart will add it autoatically.Actually in my first commit I generate the extends code `type extends type.bound`,but i found it seems to not neccesary.

**Comment by numen31337** [comment]
This solution does not add type parameters to a generated function's input like `List<T>`, it makes only `List`.

**Comment by windrunner414** [comment]
@numen31337 i will try to solve it tomorrow

**Comment by windrunner414** [comment]
I think we can get the type parameter offset in source code and use substring
We should consider this case:
```
import 'a.dart' as a;

class B<T extends a.A> {}
```
I don't find any other way to get the class prefix 'a'

**Pull request closed without merging**
